added 3 task accordion
js-tasks-ru/htmlcss-20230411_eugenia-surago pull request #5
Opened 2023-04-24 21:11 UTC by eugeniasgo

2023-04-24 21:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 21:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 12:00 UTC, GSemikozov requested changes

2023-04-25 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
лишнее ограничение

2023-04-25 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 72px;
и это тоже)

2023-04-25 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 144px;
удалим (я понимаю что это единственный способ добавить анимацию, но - в данном случае важнее функциональность чем красота)

2023-04-25 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.acc__text {
при acc__details[open] снизу другой паддинг

2023-04-25 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
если глобальный сброс - то в normalize, если в рамках компонента - то нужно использовать классы по БЭМ

2023-04-25 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
и ниже соответственно тоже)

2023-04-25 12:02 UTC, GSemikozov requested changes

2023-04-25 12:02 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +    <details class="acc__details">
элементы блока не могут существовать сами по себе вне своего блока, поэтому - надо завернуть все секции аккордиона в div с классом .acc

2023-05-01 13:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 14:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-01 15:02 UTC, GSemikozov requested changes

2023-05-01 15:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    position: absolute;
чтобы позиционировать относительно summary - надо добавить на acc__title `position: relative`

2023-05-01 15:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
не хватает стилей для описания текста

2023-05-01 16:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-02 14:07 UTC, GSemikozov requested changes

2023-05-02 14:07 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    left:   1200px;
ого))
нет, нужно так:
1. `position: relative` на .acc__title
2. `position: absolute; top: 32px; right: 32px` на .acc__arrow

2023-05-02 19:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-05 12:20 UTC, GSemikozov approved these changes, later dismissed

2023-05-07 11:57 UTC, GSemikozov approved these changes

2023-05-07 11:57 UTC, merged