04 histogram
js-tasks-ru/htmlcss-20230411_eugenia-surago pull request #6
Opened 2023-05-02 20:23 UTC by eugeniasgo

2023-05-02 20:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-03 14:42 UTC, GSemikozov requested changes

2023-05-03 14:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.hist {
что-то лишнее заехало?)

2023-05-03 14:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 300px;
max-width

2023-05-03 14:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 300px;
тут же - задаем общие паддинги

2023-05-03 14:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    color: #212429;
не забываем про font-family и прочие стили для оформления текста)

2023-05-03 14:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 39px 29px 24px 26px;
если паддинги зададим на уровне блока, то здесь - только margin-top

2023-05-03 14:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: flex;
не хватает height: 50px

2023-05-03 14:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.hist__column-max {
отсюда и ниже - все свести к 1 элементу .hist__col { flex-basis: 9px; flex-grow: 1; background: #4263EB; } а высоту ставим инлайном прям на хтмл элементе

2023-05-03 14:42 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <div class="hist__view">
это ссылка `<a>`

2023-05-05 12:20 UTC, GSemikozov approved these changes

2023-05-05 12:20 UTC, merged